name: Housekeeping

on:
  push:
    branches:
      - main
    paths-ignore:
      - "cspell.json"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  validating:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: |
          npm install -g cspell markdownlint-cli

      - name: Install yamllint
        run: python -m pip install yamllint

      - name: Ensure cspell.json Exists
        run: |
          if [ ! -f cspell.json ]; then
            echo '{"version": "0.2", "language": "en", "ignorePaths": [".devcontainer/**", ".vscode/**", ".github/**"], "ignoreWords": []}' > cspell.json
          fi

      - name: Fetch Organization Members
        env:
          AUTH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
          ORG_NAME: ${{ github.repository_owner }}
        run: |
          echo "Fetching organization members from $ORG_NAME..."
          curl -s -H "Authorization: Bearer $AUTH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/orgs/$ORG_NAME/members > .github/workflows/members.json

          echo "Fetched members.json content:"
          cat .github/workflows/members.json

      - name: Update cspell.json with Usernames
        run: python .github/workflows/update_cspell.py

      - name: Commit and Push Updates to cspell.json
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ $(git status --porcelain) ]]; then
            git add cspell.json
            git commit -m "[skip cspell] Update cspell.json with organization member names"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Run cspell
        run: |
          cspell --config ./cspell.json "./**/*.md" || echo "cspell encountered no files or an error."

      - name: Run markdownlint
        run: |
          markdownlint "./**/*.md" || echo "No markdown files found or markdownlint encountered an error."

      - name: Run yamllint
        run: yamllint .
