---
name: Housekeeping

on:
  push:
    branches:
      - main
    paths-ignore:
      - "cspell.json"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  validating:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-cache-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: |
          npm install -g cspell markdownlint-cli &
          python -m pip install yamllint &
          wait

      - name: Ensure cspell.json Exists
        run: |
          if [ ! -f cspell.json ]; then
            echo '{
              "ignoreWords": []
            }' > cspell.json
          fi

      - name: Update cspell.json with Usernames
        id: update_cspell
        env:
          AUTH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
          ORG_NAME: ${{ github.repository_owner }}
        run: python .github/workflows/update_cspell.py

      - name: Check for cspell.json Changes
        id: check_cspell_changes
        run: |
          if [[ $(git diff --name-only cspell.json) ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Updates to cspell.json
        if: env.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Enable commit signing
          git config commit.gpgSign true
          git config gpg.format ssh
          git config user.signingkey $GITHUB_TOKEN

          # Commit and push changes
          git add cspell.json
          git commit -S -m "[skip cspell] Update cspell.json with org member names"
          git push

      - name: Run cspell
        if: env.changes_detected == 'true'
        run: cspell --config ./cspell.json "./**/*.md"

      - name: Run markdownlint
        if: env.changes_detected == 'true'
        run: markdownlint "./**/*.md"

      - name: Run yamllint
        if: env.changes_detected == 'true'
        run: yamllint .
