name: Housekeeping

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  validating:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: |
          npm install -g cspell markdownlint-cli

      - name: Ensure cspell.json Exists
        run: |
          if [ ! -f cspell.json ]; then
            echo '{"version": "0.2", "language": "en", "ignorePaths": [".devcontainer/**", ".vscode/**", ".github/**"], "ignoreWords": []}' > cspell.json
          fi

      - name: Fetch Organization Members
        env:
          AUTH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
        run: |
          echo "Fetching organization members from esvies..."
          curl -s -H "Authorization: Bearer $AUTH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/orgs/esvies/members > members.json

      - name: Update cspell.json with Usernames
        run: python update_cspell.py

      - name: Run cspell
        run: |
          cspell --config ./cspell.json "./**/*.md" || echo "cspell encountered no files or an error."
